package com.example.aigc.enums;

public enum PipelineType {
    REFINE,
    ASSET_EXTRACTION,
    KEYFRAME_GENERATION,
    SHOT_SPLIT,
    VIDEO_GENERATION,
    LIP_SYNC,
    VIDEO_EDIT_PREVIEW,
    VIDEO_EDIT_PUBLISH,
    FINAL_COMPOSITION,
    EXPORT_PACKAGE
}
