package com.example.aigc.enums;

public enum ProjectStatus {
    DRAFT,
    SCRIPT_REFINING,
    SCRIPT_READY,
    ASSET_EXTRACTING,
    ASSET_READY,
    KEYFRAME_GENERATING,
    KEYFRAME_READY,
    VIDEO_GENERATING,
    DUBBING_GENERATING,
    LIP_SYNC_GENERATING,
    FINAL_COMPOSITION_GENERATING,
    EXPORT_PACKAGE_GENERATING,
    VIDEO_READY,
    DUBBING_READY,
    LIP_SYNC_READY,
    FINAL_COMPOSITION_READY,
    EXPORT_PACKAGE_READY,
    COMPLETED,
    PARTIAL_FAILED,
    FAILED
}
