ALTER TABLE user
  ADD COLUMN IF NOT EXISTS phone VARCHAR(11) NULL AFTER password_hash,
  ADD COLUMN IF NOT EXISTS openid VARCHAR(64) NULL AFTER phone,
  ADD COLUMN IF NOT EXISTS nickname VARCHAR(32) NULL AFTER openid,
  ADD COLUMN IF NOT EXISTS avatar VARCHAR(255) NULL AFTER nickname,
  ADD COLUMN IF NOT EXISTS update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_phone ON user (phone);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_openid ON user (openid);
