CREATE TABLE IF NOT EXISTS dubbing_task (
    dubbing_task_id VARCHAR(64) PRIMARY KEY,
    project_id VARCHAR(64) NOT NULL,
    shot_id VARCHAR(64) NULL,
    request_payload_file_id VARCHAR(64) NULL,
    result_audio_file_id VARCHAR(64) NULL,
    provider_task_id VARCHAR(128) NULL,
    model_name VARCHAR(255) NULL,
    language VARCHAR(64) NULL,
    voice_name VARCHAR(128) NULL,
    speech_rate DOUBLE NULL,
    input_text LONGTEXT NULL,
    status VARCHAR(64) NULL,
    retry_count INT NULL,
    started_at TIMESTAMP NULL,
    finished_at TIMESTAMP NULL,
    error_message TEXT NULL,
    INDEX idx_dubbing_task_project_id (project_id),
    INDEX idx_dubbing_task_shot_id (shot_id),
    INDEX idx_dubbing_task_started_at (started_at)
);

CREATE TABLE IF NOT EXISTS lip_sync_task (
    lip_sync_task_id VARCHAR(64) PRIMARY KEY,
    project_id VARCHAR(64) NOT NULL,
    shot_id VARCHAR(64) NULL,
    source_video_file_id VARCHAR(64) NULL,
    source_audio_file_id VARCHAR(64) NULL,
    request_payload_file_id VARCHAR(64) NULL,
    result_video_file_id VARCHAR(64) NULL,
    provider_task_id VARCHAR(128) NULL,
    model_name VARCHAR(255) NULL,
    status VARCHAR(64) NULL,
    retry_count INT NULL,
    started_at TIMESTAMP NULL,
    finished_at TIMESTAMP NULL,
    error_message TEXT NULL,
    INDEX idx_lip_sync_task_project_id (project_id),
    INDEX idx_lip_sync_task_shot_id (shot_id),
    INDEX idx_lip_sync_task_started_at (started_at)
);

CREATE TABLE IF NOT EXISTS export_package_task (
    export_package_task_id VARCHAR(64) PRIMARY KEY,
    project_id VARCHAR(64) NOT NULL,
    source_final_composition_task_id VARCHAR(64) NULL,
    source_final_video_file_id VARCHAR(64) NULL,
    manifest_file_id VARCHAR(64) NULL,
    result_archive_file_id VARCHAR(64) NULL,
    status VARCHAR(64) NULL,
    retry_count INT NULL,
    started_at TIMESTAMP NULL,
    finished_at TIMESTAMP NULL,
    error_message TEXT NULL,
    archive_storage_provider VARCHAR(32) NULL,
    archive_bucket_name VARCHAR(255) NULL,
    archive_object_key VARCHAR(1024) NULL,
    archive_public_url VARCHAR(1024) NULL,
    manifest_storage_provider VARCHAR(32) NULL,
    manifest_bucket_name VARCHAR(255) NULL,
    manifest_object_key VARCHAR(1024) NULL,
    manifest_public_url VARCHAR(1024) NULL,
    INDEX idx_export_package_task_project_id (project_id),
    INDEX idx_export_package_task_started_at (started_at)
);
